### ISSUE TITLE
How do i run the server ?

### ISSUE THREAD

**Issue by SashaRomanov** [exmex/UnityMob-server#1]
I can't find any documentation on how to run this server ?

**Comment by exmex** [comment]
There is nothing to document. Just compile, and run the generated executable.

**Comment by SashaRomanov** [comment]
How can i compile it, do i use Unity ?

Do i build it like a dotnet app, using this command

`dotnet build --runtime ubuntu.20.04-x64`

then do I run the server as independent Linux based app ?

**Comment by exmex** [comment]
I have no idea about linux C# compiling.

You open MobaServer.sln and hit build. Then execute the generated exe.

Since this is not a tutorial on how to build C# applications I'm going to close this here as this is not an issue with the repository / code inside it.
