### ISSUE TITLE
the name attrib doesn't exist in the current context ?

### ISSUE THREAD

**Issue by SashaRomanov** [exmex/UnityMob-server#2]
I'm getting an error in Program.cs file line 73 and 75 that attrib doesn't exist in the current context how can i solve this issue

and when i try to login in if i commented this function AddAllMethodsFromType

i get this error

Accepted client
>>> ch:Primary receiving 133->98 body: {
"Type": "Login",
"UserName": "hello",
"Password": "world",
"DeviceType": "All",
"DeviceId": "6969696969696969697"
}
Unknown Packet (Primary): Login

so the problem is in AddAllMethodsFromType
and i can't figure out how to solve this problem

```
private static int AddAllMethodsFromType(IEnumerable<Type> types)
        {
            var i = 0;
            foreach (var type in types)
            foreach (var method in type.GetMethods())
            foreach (var boxedAttrib in method.GetCustomAttributes(typeof(PacketAttribute), false))
            {
                
                if (!(boxedAttrib is PacketAttribute attrib)) continue; // here attrib is not defined

                var id = attrib.Id; // here is unreachable code
                var parser = (Action<Packet>) Delegate.CreateDelegate(typeof(Action<Packet>), method);

                SetParser(id, parser);

#if DEBUG
                i++;
#endif
            }

            return i;
        }
```

after solving this problem now when i try to start a match i get this in the console 

>>> ch:Primary receiving 665->277 body:{
  "Type": "NotifyPartyChange",
  "MMaxCount": 1,
  "BMainType": 1.0,
  "BSubType": 51.0,
  "AllowGradeCategorys": "",
  "Members": [
    {
      "PlayerId": 1,
      "PlayerName": "Test",
      "PlayerAvatar": "I11000301",
      "AvatarFrameId": "1",
      "Vip": 1,
      "Level": 1,
      "GradeName": "",
      "GuildName": "Staff",
      "GuildPosition": 1,
      "Status": 1
    }
  ],
  "Leader": {
    "PlayerId": 1,
    "PlayerName": "Test",
    "PlayerAvatar": "I11000301",
    "AvatarFrameId": "1",
    "Vip": 1,
    "Level": 1,
    "GradeName": "",
    "GuildName": "Staff",
    "GuildPosition": 1,
    "Status": 1
  }
}

but the level doesn't load. nothing happens

**Comment by exmex** [comment]
You need to use NET Framework v4.7.1

Of course it won't work if you comment out the function / vital part which adds the packet parsers

You could also replace this

```
if (!(boxedAttrib is PacketAttribute attrib)) continue;
```

with this:

```
var attrib = (PacketAttribute)boxedAttrib;
if (!(attrib is PacketAttribute)) continue;

**Comment by SashaRomanov** [comment]
ok but now i can't enter a match in pvp or any. is this a problem of unfinished code or i have done something wrong

**Comment by exmex** [comment]
You can see the current status of the code [here](https://github.com/exmex/UnityMoba-server/blob/master/README.md#status) in the README.md:

![image](https://user-images.githubusercontent.com/5639139/87121439-07778880-c283-11ea-9630-8a254e1c181f.png)

So yes, the only thing that works is login. Nothing else

**Comment by SashaRomanov** [comment]
ok great so client side source code is working properly only server side is needed to provide the data to client side even if its fake data is that right ?

**Comment by exmex** [comment]
Yes

**Comment by irfanyusuf** [comment]
How to run this Server? Any Guide?

**Comment by exmex** [comment]
Compile and run the server?
